### ISSUE TITLE
The error while running rsitesearch.py

### ISSUE THREAD

**Issue by NextGenBioinformatics** [GGFHF/ddRADseqTools#6]
Hello,

I am using ddRADseqTools to analyse the data but after installation I encounter an error message while trying to test the program "rsitesearch.py". 

The version of python is Python 3.7.0.

Would you like to help me out?

Thanks a million,

Kind regards

Tom

```
./rsitesearch.py --help



ERROR:root:code for hash sha3_224 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_224'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_224
ERROR:root:code for hash sha3_256 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_256
ERROR:root:code for hash sha3_384 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_384'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_384
ERROR:root:code for hash sha3_512 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_sha3_512'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha3_512
ERROR:root:code for hash shake_128 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_128
ERROR:root:code for hash shake_256 was not found.
Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 121, in __get_openssl_constructor
    f = getattr(_hashlib, 'openssl_' + name)
AttributeError: module '_hashlib' has no attribute 'openssl_shake_256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 243, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 128, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "Python-3.7.0/Python-3.7.0/lib/python3.7/hashlib.py", line 113, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type shake_256

ddRADseqTools version 0.45

rsitesearch.py searches the restriction sites of a genome, do a double digestion and write a file in FASTA format with the fragments gotten.

Usage: rsitesearch.py --help

       Show the help of rsitesearch.py.

   or: rsitesearch.py --config

       Create the config file ./rsitesearch-config.txt with the default value of the options.
       The default value of the options can be modified.

   or: rsitesearch.py [--option=<value> [--option=<value>, ...]]

       The options values are read from the config file ./rsitesearch-config.txt, but they can be modified
       in command line. The options are:

       option             value
       ================   ==============================================================================
       --genfile          file of the reference genome in fasta format
       --fragsfile        path of the fragments file
       --rsfile           path of the restriction sites file
       --enzyme1          id of 1st restriction enzyme used in rsfile or its restriction site sequence
       --enzyme2          id of 2nd restriction enzyme used in rsfile or its restriction site sequence
       --minfragsize      lower boundary of loci fragment's size
       --maxfragsize      upper boundary of loci fragment's size
       --fragstfile       path of the fragment statistics file
       --fragstinterval   interval length of fragment size
       --plot             statistical graphs: YES or NO
       --verbose          additional job status info during the run: YES or NO
       --trace            additional info useful to the developer team: YES or NO

```

**Comment by GGFHF** [comment]
Dear Tom,

 thanks for using ddRADseqTools. We tested ddRADseqTools with python3.7 on a Windows machine, and it worked perfectly. Could you tell us which is your OS, and how did you install Python3.7? Did you have a pre-installed python version?
 we are performing some tests on Ubuntu environments, and, hopefully we'll be able to give you some advice very soon.

All the best,

Unai and Fernando

**Comment by fernandomoramarquez** [comment]
Dear Tom, 

We have just installed Python 3.7.0 on an Ubuntu 18.04 machine, and ddRADseqTools also worked. We think your Python 3.7.0 setup is not right. However, please tell us which is your OS and how did you install Python 3.7.0, and we will try to help you. An aditional question, have you installed NumPy and matplotlib libraries?

All the best,
Unai and Fernando
